<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="Shouldly" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Unchained.Pdf.Rendering.Proprietary\Unchained.Pdf.Rendering.Proprietary.csproj" />
    <ProjectReference Include="..\..\src\Unchained.Pptx.Rendering\Unchained.Pptx.Rendering.csproj" />
    <ProjectReference Include="..\Unchained.Pptx.Tests.Shared\Unchained.Pptx.Tests.Shared.csproj" />
  </ItemGroup>

</Project>
