using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("Unchained.Drawing")]
[assembly: InternalsVisibleTo("Unchained.Drawing.Text")]
[assembly: InternalsVisibleTo("Unchained.Ooxml")]
[assembly: InternalsVisibleTo("Unchained.Pdf")]
[assembly: InternalsVisibleTo("Unchained.Pdf.Rendering")]
[assembly: InternalsVisibleTo("Unchained.Pptx")]
[assembly: InternalsVisibleTo("Unchained.Pptx.Rendering")]
[assembly: InternalsVisibleTo("Unchained.Pdf.Tests")]
[assembly: InternalsVisibleTo("Unchained.Pptx.Tests")]
[assembly: InternalsVisibleTo("Unchained.Ooxml.Tests")]
[assembly: InternalsVisibleTo("Unchained.Diagnose")]
[assembly: InternalsVisibleTo("Unchained.BatchCompare")]
[assembly: InternalsVisibleTo("Unchained.Render")]
[assembly: InternalsVisibleTo("Unchained.Studio")]
